name: Hello World

on:
  push:
    branches:
      - main
      - feature/*


jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Building docker image
        run: docker build -t my-nginx-image .
        
